#!/bin/bash

# Update package lists
apt-get update -y > /dev/null 2>&1

# Install Nginx
apt-get install nginx -y > /dev/null 2>&1

# Configure Nginx to listen on port 80
sed -i 's/listen\s*80;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart > /dev/null 2>&1

# Create index.html with "Hello World!" content
echo 'Hello World!' > /var/www/html/index.html

