#!/usr/bin/env bash
# Install and configure HAProxy load balancer

echo -e "Updating and performing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
        sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "$1 is already installed.\n"
    fi
}

install haproxy

echo -e "\nSetting up some minor configurations...\n"

# Backup default HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define HAProxy configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend clickviral-tech-frontend
    bind *:80
    default_backend clickviral-tech-backend

backend clickviral-tech-backend
    balance roundrobin
    server 502383-web-02 100.26.240.240:80 check
    server 502383-lb-01 54.237.81.248:80 check
"

# Update HAProxy configuration file
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "Configured: Round-robin between web-02 & lb-01"

# Start or restart HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

