#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server

# Update package lists
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 3.85.175.42:80 check
    server web-02 100.26.240.240:80 check
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Ensure HAProxy is enabled to start on boot
sudo systemctl enable haproxy

