#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100
# Displays "FizzBuzz" when the number is a multiple of 3 and 5
# Displays "Fizz" when the number is a multiple of 3
# Displays "Buzz" when the number is a multiple of 5
# Otherwise, displays the number in list format

for u in {1..100}
do
  if (( u % 3 == 0 && u % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( u % 3 == 0 ))
  then
    echo "Fizz"
  elif (( u % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$u"
  fi
done
