#!/usr/bin/env bash
# Bash script that loops from 1 to 10
# Displays bad luck for the 4th loop iteration
# Good luck for the 8th loop iteration
# Best School for the other iterations with while loop

u=0

while [ $u -lt 10 ]
do
  if [ $u -eq 3 ]
  then
    echo "bad luck"
  elif [ $u -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( u++ ))
done
