#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
# Displays 4 and then bad luck from China for the 4th loop iteration
# Displays 9 and then bad luck from Japan for the 9th loop iteration
# Displays 17 and then bad luck from Italy for the 17th loop iteration
# With the while loop

u=1

while [ $u -le 20 ]
do
  echo "$u"
  case $u in
    "4") echo "bad luck from China";;
    "9") echo "bad luck from Japan";;
    "17") echo "bad luck from Italy";;
  esac
  (( u++ ))
done
